name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: document.tex
